version: '3'
services:
  common-build:
    build:
      context: ./common
      dockerfile: Dockerfile
    image: common-build
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"